export const autocompleteData = [
  { name: 'Bulbasaur', id: 1, japanese: 'フシギダネ', chinese: '妙蛙种子' },
  { name: 'Ivysaur', id: 2, japanese: 'フシギソウ', chinese: '妙蛙草' },
  { name: 'Venusaur', id: 3, japanese: 'フシギバナ', chinese: '妙蛙花' },
  { name: 'Charmander', id: 4, japanese: 'ヒトカゲ', chinese: '小火龙' },
  { name: 'Charmeleon', id: 5, japanese: 'リザード', chinese: '火恐龙' },
  { name: 'Charizard', id: 6, japanese: 'リザードン', chinese: '喷火龙' },
  { name: 'Squirtle', id: 7, japanese: 'ゼニガメ', chinese: '杰尼龟' },
  { name: 'Wartortle', id: 8, japanese: 'カメール', chinese: '卡咪龟' },
  { name: 'Blastoise', id: 9, japanese: 'カメックス', chinese: '水箭龟' },
  { name: 'Caterpie', id: 10, japanese: 'キャタピー', chinese: '绿毛虫' },
  { name: 'Metapod', id: 11, japanese: 'トランセル', chinese: '铁甲蛹' },
  { name: 'Butterfree', id: 12, japanese: 'バタフリー', chinese: '巴大蝶' },
  { name: 'Weedle', id: 13, japanese: 'ビードル', chinese: '独角虫' },
  { name: 'Kakuna', id: 14, japanese: 'コクーン', chinese: '铁壳蛹' },
  { name: 'Beedrill', id: 15, japanese: 'スピアー', chinese: '大针蜂' },
  { name: 'Pidgey', id: 16, japanese: 'ポッポ', chinese: '波波' },
  { name: 'Pidgeotto', id: 17, japanese: 'ピジョン', chinese: '比比鸟' },
  { name: 'Pidgeot', id: 18, japanese: 'ピジョット', chinese: '大比鸟' },
  { name: 'Rattata', id: 19, japanese: 'コラッタ', chinese: '小拉达' },
  { name: 'Raticate', id: 20, japanese: 'ラッタ', chinese: '拉达' },
  { name: 'Spearow', id: 21, japanese: 'オニスズメ', chinese: '烈雀' },
  { name: 'Fearow', id: 22, japanese: 'オニドリル', chinese: '大嘴雀' },
  { name: 'Ekans', id: 23, japanese: 'アーボ', chinese: '阿柏蛇' },
  { name: 'Arbok', id: 24, japanese: 'アーボック', chinese: '阿柏怪' },
  { name: 'Pikachu', id: 25, japanese: 'ピカチュウ', chinese: '皮卡丘' },
  { name: 'Raichu', id: 26, japanese: 'ライチュウ', chinese: '雷丘' },
  { name: 'Sandshrew', id: 27, japanese: 'サンド', chinese: '穿山鼠' },
  { name: 'Sandslash', id: 28, japanese: 'サンドパン', chinese: '穿山王' },
  { name: 'Nidoran-F', id: 29, japanese: 'ニドラン', chinese: '尼多兰' },
  { name: 'Nidorina', id: 30, japanese: 'ニドリーナ', chinese: '尼多娜' },
  { name: 'Nidoqueen', id: 31, japanese: 'ニドクイン', chinese: '尼多后' },
  { name: 'Nidoran-M', id: 32, japanese: 'ニドラン', chinese: '尼多朗' },
  { name: 'Nidorino', id: 33, japanese: 'ニドリーノ', chinese: '尼多力诺' },
  { name: 'Nidoking', id: 34, japanese: 'ニドキング', chinese: '尼多王' },
  { name: 'Clefairy', id: 35, japanese: 'ピッピ', chinese: '皮皮' },
  { name: 'Clefable', id: 36, japanese: 'ピクシー', chinese: '皮可西' },
  { name: 'Vulpix', id: 37, japanese: 'ロコン', chinese: '六尾' },
  { name: 'Ninetales', id: 38, japanese: 'キュウコン', chinese: '九尾' },
  { name: 'Jigglypuff', id: 39, japanese: 'プリン', chinese: '胖丁' },
  { name: 'Wigglytuff', id: 40, japanese: 'プクリン', chinese: '胖可丁' },
  { name: 'Zubat', id: 41, japanese: 'ズバット', chinese: '超音蝠' },
  { name: 'Golbat', id: 42, japanese: 'ゴルバット', chinese: '大嘴蝠' },
  { name: 'Oddish', id: 43, japanese: 'ナゾノクサ', chinese: '走路草' },
  { name: 'Gloom', id: 44, japanese: 'クサイハナ', chinese: '臭臭花' },
  { name: 'Vileplume', id: 45, japanese: 'ラフレシア', chinese: '霸王花' },
  { name: 'Paras', id: 46, japanese: 'パラス', chinese: '派拉斯' },
  { name: 'Parasect', id: 47, japanese: 'パラセクト', chinese: '派拉斯特' },
  { name: 'Venonat', id: 48, japanese: 'コンパン', chinese: '毛球' },
  { name: 'Venomoth', id: 49, japanese: 'モルフォン', chinese: '摩鲁蛾' },
  { name: 'Diglett', id: 50, japanese: 'ディグダ', chinese: '地鼠' },
  { name: 'Dugtrio', id: 51, japanese: 'ダグトリオ', chinese: '三地鼠' },
  { name: 'Meowth', id: 52, japanese: 'ニャース', chinese: '喵喵' },
  { name: 'Persian', id: 53, japanese: 'ペルシアン', chinese: '猫老大' },
  { name: 'Psyduck', id: 54, japanese: 'コダック', chinese: '可达鸭' },
  { name: 'Golduck', id: 55, japanese: 'ゴルダック', chinese: '哥达鸭' },
  { name: 'Mankey', id: 56, japanese: 'マンキー', chinese: '猴怪' },
  { name: 'Primeape', id: 57, japanese: 'オコリザル', chinese: '火暴猴' },
  { name: 'Growlithe', id: 58, japanese: 'ガーディ', chinese: '卡蒂狗' },
  { name: 'Arcanine', id: 59, japanese: 'ウインディ', chinese: '风速狗' },
  { name: 'Poliwag', id: 60, japanese: 'ニョロモ', chinese: '蚊香蝌蚪' },
  { name: 'Poliwhirl', id: 61, japanese: 'ニョロゾ', chinese: '蚊香君' },
  { name: 'Poliwrath', id: 62, japanese: 'ニョロボン', chinese: '蚊香泳士' },
  { name: 'Abra', id: 63, japanese: 'ケーシィ', chinese: '凯西' },
  { name: 'Kadabra', id: 64, japanese: 'ユンゲラー', chinese: '勇基拉' },
  { name: 'Alakazam', id: 65, japanese: 'フーディン', chinese: '胡地' },
  { name: 'Machop', id: 66, japanese: 'ワンリキー', chinese: '腕力' },
  { name: 'Machoke', id: 67, japanese: 'ゴーリキー', chinese: '豪力' },
  { name: 'Machamp', id: 68, japanese: 'カイリキー', chinese: '怪力' },
  { name: 'Bellsprout', id: 69, japanese: 'マダツボミ', chinese: '喇叭芽' },
  { name: 'Weepinbell', id: 70, japanese: 'ウツドン', chinese: '口呆花' },
  { name: 'Victreebel', id: 71, japanese: 'ウツボット', chinese: '大食花' },
  { name: 'Tentacool', id: 72, japanese: 'メノクラゲ', chinese: '玛瑙水母' },
  { name: 'Tentacruel', id: 73, japanese: 'ドククラゲ', chinese: '毒刺水母' },
  { name: 'Geodude', id: 74, japanese: 'イシツブテ', chinese: '小拳石' },
  { name: 'Graveler', id: 75, japanese: 'ゴローン', chinese: '隆隆石' },
  { name: 'Golem', id: 76, japanese: 'ゴローニャ', chinese: '隆隆岩' },
  { name: 'Ponyta', id: 77, japanese: 'ポニータ', chinese: '小火马' },
  { name: 'Rapidash', id: 78, japanese: 'ギャロップ', chinese: '烈焰马' },
  { name: 'Slowpoke', id: 79, japanese: 'ヤドン', chinese: '呆呆兽' },
  { name: 'Slowbro', id: 80, japanese: 'ヤドラン', chinese: '呆壳兽' },
  { name: 'Magnemite', id: 81, japanese: 'コイル', chinese: '小磁怪' },
  { name: 'Magneton', id: 82, japanese: 'レアコイル', chinese: '三合一磁怪' },
  { name: 'Farfetchd', id: 83, japanese: 'カモネギ', chinese: '大葱鸭' },
  { name: 'Doduo', id: 84, japanese: 'ドードー', chinese: '嘟嘟' },
  { name: 'Dodrio', id: 85, japanese: 'ドードリオ', chinese: '嘟嘟利' },
  { name: 'Seel', id: 86, japanese: 'パウワウ', chinese: '小海狮' },
  { name: 'Dewgong', id: 87, japanese: 'ジュゴン', chinese: '白海狮' },
  { name: 'Grimer', id: 88, japanese: 'ベトベター', chinese: '臭泥' },
  { name: 'Muk', id: 89, japanese: 'ベトベトン', chinese: '臭臭泥' },
  { name: 'Shellder', id: 90, japanese: 'シェルダー', chinese: '大舌贝' },
  { name: 'Cloyster', id: 91, japanese: 'パルシェン', chinese: '刺甲贝' },
  { name: 'Gastly', id: 92, japanese: 'ゴース', chinese: '鬼斯' },
  { name: 'Haunter', id: 93, japanese: 'ゴースト', chinese: '鬼斯通' },
  { name: 'Gengar', id: 94, japanese: 'ゲンガー', chinese: '耿鬼' },
  { name: 'Onix', id: 95, japanese: 'イワーク', chinese: '大岩蛇' },
  { name: 'Drowzee', id: 96, japanese: 'スリープ', chinese: '催眠貘' },
  { name: 'Hypno', id: 97, japanese: 'スリーパー', chinese: '引梦貘人' },
  { name: 'Krabby', id: 98, japanese: 'クラブ', chinese: '大钳蟹' },
  { name: 'Kingler', id: 99, japanese: 'キングラー', chinese: '巨钳蟹' },
  { name: 'Voltorb', id: 100, japanese: 'ビリリダマ', chinese: '霹雳电球' },
  { name: 'Electrode', id: 101, japanese: 'マルマイン', chinese: '顽皮雷弹' },
  { name: 'Exeggcute', id: 102, japanese: 'タマタマ', chinese: '蛋蛋' },
  { name: 'Exeggutor', id: 103, japanese: 'ナッシー', chinese: '椰蛋树' },
  { name: 'Cubone', id: 104, japanese: 'カラカラ', chinese: '卡拉卡拉' },
  { name: 'Marowak', id: 105, japanese: 'ガラガラ', chinese: '嘎啦嘎啦' },
  { name: 'Hitmonlee', id: 106, japanese: 'サワムラー', chinese: '飞腿郎' },
  { name: 'Hitmonchan', id: 107, japanese: 'エビワラー', chinese: '快拳郎' },
  { name: 'Lickitung', id: 108, japanese: 'ベロリンガ', chinese: '大舌头' },
  { name: 'Koffing', id: 109, japanese: 'ドガース', chinese: '瓦斯弹' },
  { name: 'Weezing', id: 110, japanese: 'マタドガス', chinese: '双弹瓦斯' },
  { name: 'Rhyhorn', id: 111, japanese: 'サイホーン', chinese: '独角犀牛' },
  { name: 'Rhydon', id: 112, japanese: 'サイドン', chinese: '钻角犀兽' },
  { name: 'Chansey', id: 113, japanese: 'ラッキー', chinese: '吉利蛋' },
  { name: 'Tangela', id: 114, japanese: 'モンジャラ', chinese: '蔓藤怪' },
  { name: 'Kangaskhan', id: 115, japanese: 'ガルーラ', chinese: '袋兽' },
  { name: 'Horsea', id: 116, japanese: 'タッツー', chinese: '墨海马' },
  { name: 'Seadra', id: 117, japanese: 'シードラ', chinese: '海刺龙' },
  { name: 'Goldeen', id: 118, japanese: 'トサキント', chinese: '角金鱼' },
  { name: 'Seaking', id: 119, japanese: 'アズマオウ', chinese: '金鱼王' },
  { name: 'Staryu', id: 120, japanese: 'ヒトデマン', chinese: '海星星' },
  { name: 'Starmie', id: 121, japanese: 'スターミー', chinese: '宝石海星' },
  { name: 'Mr-Mime', id: 122, japanese: 'バリヤード', chinese: '魔墙人偶' },
  { name: 'Scyther', id: 123, japanese: 'ストライク', chinese: '飞天螳螂' },
  { name: 'Jynx', id: 124, japanese: 'ルージュラ', chinese: '迷唇姐' },
  { name: 'Electabuzz', id: 125, japanese: 'エレブー', chinese: '电击兽' },
  { name: 'Magmar', id: 126, japanese: 'ブーバー', chinese: '鸭嘴火兽' },
  { name: 'Pinsir', id: 127, japanese: 'カイロス', chinese: '凯罗斯' },
  { name: 'Tauros', id: 128, japanese: 'ケンタロス', chinese: '肯泰罗' },
  { name: 'Magikarp', id: 129, japanese: 'コイキング', chinese: '鲤鱼王' },
  { name: 'Gyarados', id: 130, japanese: 'ギャラドス', chinese: '暴鲤龙' },
  { name: 'Lapras', id: 131, japanese: 'ラプラス', chinese: '拉普拉斯' },
  { name: 'Ditto', id: 132, japanese: 'メタモン', chinese: '百变怪' },
  { name: 'Eevee', id: 133, japanese: 'イーブイ', chinese: '伊布' },
  { name: 'Vaporeon', id: 134, japanese: 'シャワーズ', chinese: '水伊布' },
  { name: 'Jolteon', id: 135, japanese: 'サンダース', chinese: '雷伊布' },
  { name: 'Flareon', id: 136, japanese: 'ブースター', chinese: '火伊布' },
  { name: 'Porygon', id: 137, japanese: 'ポリゴン', chinese: '多边兽' },
  { name: 'Omanyte', id: 138, japanese: 'オムナイト', chinese: '菊石兽' },
  { name: 'Omastar', id: 139, japanese: 'オムスター', chinese: '多刺菊石兽' },
  { name: 'Kabuto', id: 140, japanese: 'カブト', chinese: '化石盔' },
  { name: 'Kabutops', id: 141, japanese: 'カブトプス', chinese: '镰刀盔' },
  { name: 'Aerodactyl', id: 142, japanese: 'プテラ', chinese: '化石翼龙' },
  { name: 'Snorlax', id: 143, japanese: 'カビゴン', chinese: '卡比兽' },
  { name: 'Articuno', id: 144, japanese: 'フリーザー', chinese: '急冻鸟' },
  { name: 'Zapdos', id: 145, japanese: 'サンダー', chinese: '闪电鸟' },
  { name: 'Moltres', id: 146, japanese: 'ファイヤー', chinese: '火焰鸟' },
  { name: 'Dratini', id: 147, japanese: 'ミニリュウ', chinese: '迷你龙' },
  { name: 'Dragonair', id: 148, japanese: 'ハクリュー', chinese: '哈克龙' },
  { name: 'Dragonite', id: 149, japanese: 'カイリュー', chinese: '快龙' },
  { name: 'Mewtwo', id: 150, japanese: 'ミュウツー', chinese: '超梦' },
  { name: 'Mew', id: 151, japanese: 'ミュウ', chinese: '梦幻' },
  { name: 'Chikorita', id: 152, japanese: 'チコリータ', chinese: '菊草叶' },
  { name: 'Bayleef', id: 153, japanese: 'ベイリーフ', chinese: '月桂叶' },
  { name: 'Meganium', id: 154, japanese: 'メガニウム', chinese: '大竺葵' },
  { name: 'Cyndaquil', id: 155, japanese: 'ヒノアラシ', chinese: '火球鼠' },
  { name: 'Quilava', id: 156, japanese: 'マグマラシ', chinese: '火岩鼠' },
  { name: 'Typhlosion', id: 157, japanese: 'バクフーン', chinese: '火暴兽' },
  { name: 'Totodile', id: 158, japanese: 'ワニノコ', chinese: '小锯鳄' },
  { name: 'Croconaw', id: 159, japanese: 'アリゲイツ', chinese: '蓝鳄' },
  { name: 'Feraligatr', id: 160, japanese: 'オーダイル', chinese: '大力鳄' },
  { name: 'Sentret', id: 161, japanese: 'オタチ', chinese: '尾立' },
  { name: 'Furret', id: 162, japanese: 'オオタチ', chinese: '大尾立' },
  { name: 'Hoothoot', id: 163, japanese: 'ホーホー', chinese: '咕咕' },
  { name: 'Noctowl', id: 164, japanese: 'ヨルノズク', chinese: '猫头夜鹰' },
  { name: 'Ledyba', id: 165, japanese: 'レディバ', chinese: '芭瓢虫' },
  { name: 'Ledian', id: 166, japanese: 'レディアン', chinese: '安瓢虫' },
  { name: 'Spinarak', id: 167, japanese: 'イトマル', chinese: '圆丝蛛' },
  { name: 'Ariados', id: 168, japanese: 'アリアドス', chinese: '阿利多斯' },
  { name: 'Crobat', id: 169, japanese: 'クロバット', chinese: '叉字蝠' },
  { name: 'Chinchou', id: 170, japanese: 'チョンチー', chinese: '灯笼鱼' },
  { name: 'Lanturn', id: 171, japanese: 'ランターン', chinese: '电灯怪' },
  { name: 'Pichu', id: 172, japanese: 'ピチュー', chinese: '皮丘' },
  { name: 'Cleffa', id: 173, japanese: 'ピィ', chinese: '皮宝宝' },
  { name: 'Igglybuff', id: 174, japanese: 'ププリン', chinese: '宝宝丁' },
  { name: 'Togepi', id: 175, japanese: 'トゲピー', chinese: '波克比' },
  { name: 'Togetic', id: 176, japanese: 'トゲチック', chinese: '波克基古' },
  { name: 'Natu', id: 177, japanese: 'ネイティ', chinese: '天然雀' },
  { name: 'Xatu', id: 178, japanese: 'ネイティオ', chinese: '天然鸟' },
  { name: 'Mareep', id: 179, japanese: 'メリープ', chinese: '咩利羊' },
  { name: 'Flaaffy', id: 180, japanese: 'モココ', chinese: '茸茸羊' },
  { name: 'Ampharos', id: 181, japanese: 'デンリュウ', chinese: '电龙' },
  { name: 'Bellossom', id: 182, japanese: 'キレイハナ', chinese: '美丽花' },
  { name: 'Marill', id: 183, japanese: 'マリル', chinese: '玛力露' },
  { name: 'Azumarill', id: 184, japanese: 'マリルリ', chinese: '玛力露丽' },
  {
    name: 'Sudowoodo',
    id: 185,
    japanese: 'ウソッキー',
    chinese: '树才怪\u200e',
  },
  { name: 'Politoed', id: 186, japanese: 'ニョロトノ', chinese: '蚊香蛙皇' },
  { name: 'Hoppip', id: 187, japanese: 'ハネッコ', chinese: '毽子草' },
  { name: 'Skiploom', id: 188, japanese: 'ポポッコ', chinese: '毽子花' },
  { name: 'Jumpluff', id: 189, japanese: 'ワタッコ', chinese: '毽子棉' },
  { name: 'Aipom', id: 190, japanese: 'エイパム', chinese: '长尾怪手' },
  { name: 'Sunkern', id: 191, japanese: 'ヒマナッツ', chinese: '向日种子' },
  { name: 'Sunflora', id: 192, japanese: 'キマワリ', chinese: '向日花怪' },
  { name: 'Yanma', id: 193, japanese: 'ヤンヤンマ', chinese: '蜻蜻蜓' },
  { name: 'Wooper', id: 194, japanese: 'ウパー', chinese: '乌波' },
  { name: 'Quagsire', id: 195, japanese: 'ヌオー', chinese: '沼王' },
  { name: 'Espeon', id: 196, japanese: 'エーフィ', chinese: '太阳伊布' },
  { name: 'Umbreon', id: 197, japanese: 'ブラッキー', chinese: '月亮伊布' },
  { name: 'Murkrow', id: 198, japanese: 'ヤミカラス', chinese: '黑暗鸦' },
  { name: 'Slowking', id: 199, japanese: 'ヤドキング', chinese: '呆呆王' },
  { name: 'Misdreavus', id: 200, japanese: 'ムウマ', chinese: '梦妖' },
  { name: 'Unown', id: 201, japanese: 'アンノーン', chinese: '未知图腾' },
  { name: 'Wobbuffet', id: 202, japanese: 'ソーナンス', chinese: '果然翁' },
  { name: 'Girafarig', id: 203, japanese: 'キリンリキ', chinese: '麒麟奇' },
  { name: 'Pineco', id: 204, japanese: 'クヌギダマ', chinese: '榛果球' },
  { name: 'Forretress', id: 205, japanese: 'フォレトス', chinese: '佛烈托斯' },
  { name: 'Dunsparce', id: 206, japanese: 'ノコッチ', chinese: '土龙弟弟' },
  { name: 'Gligar', id: 207, japanese: 'グライガー', chinese: '天蝎' },
  { name: 'Steelix', id: 208, japanese: 'ハガネール', chinese: '大钢蛇' },
  { name: 'Snubbull', id: 209, japanese: 'ブルー', chinese: '布鲁' },
  { name: 'Granbull', id: 210, japanese: 'グランブル', chinese: '布鲁皇' },
  { name: 'Qwilfish', id: 211, japanese: 'ハリーセン', chinese: '千针鱼' },
  { name: 'Scizor', id: 212, japanese: 'ハッサム', chinese: '巨钳螳螂' },
  { name: 'Shuckle', id: 213, japanese: 'ツボツボ', chinese: '壶壶' },
  { name: 'Heracross', id: 214, japanese: 'ヘラクロス', chinese: '赫拉克罗斯' },
  { name: 'Sneasel', id: 215, japanese: 'ニューラ', chinese: '狃拉' },
  { name: 'Teddiursa', id: 216, japanese: 'ヒメグマ', chinese: '熊宝宝' },
  { name: 'Ursaring', id: 217, japanese: 'リングマ', chinese: '圈圈熊' },
  { name: 'Slugma', id: 218, japanese: 'マグマッグ', chinese: '熔岩虫' },
  { name: 'Magcargo', id: 219, japanese: 'マグカルゴ', chinese: '熔岩蜗牛' },
  { name: 'Swinub', id: 220, japanese: 'ウリムー', chinese: '小山猪' },
  { name: 'Piloswine', id: 221, japanese: 'イノムー', chinese: '长毛猪' },
  { name: 'Corsola', id: 222, japanese: 'サニーゴ', chinese: '太阳珊瑚' },
  { name: 'Remoraid', id: 223, japanese: 'テッポウオ', chinese: '铁炮鱼' },
  { name: 'Octillery', id: 224, japanese: 'オクタン', chinese: '章鱼桶' },
  { name: 'Delibird', id: 225, japanese: 'デリバード', chinese: '信使鸟' },
  { name: 'Mantine', id: 226, japanese: 'マンタイン', chinese: '巨翅飞鱼' },
  { name: 'Skarmory', id: 227, japanese: 'エアームド', chinese: '盔甲鸟' },
  { name: 'Houndour', id: 228, japanese: 'デルビル', chinese: '戴鲁比' },
  { name: 'Houndoom', id: 229, japanese: 'ヘルガー', chinese: '黑鲁加' },
  { name: 'Kingdra', id: 230, japanese: 'キングドラ', chinese: '刺龙王' },
  { name: 'Phanpy', id: 231, japanese: 'ゴマゾウ', chinese: '小小象' },
  { name: 'Donphan', id: 232, japanese: 'ドンファン', chinese: '顿甲' },
  { name: 'Porygon2', id: 233, japanese: 'ポリゴン２', chinese: '多边兽Ⅱ' },
  { name: 'Stantler', id: 234, japanese: 'オドシシ', chinese: '惊角鹿' },
  { name: 'Smeargle', id: 235, japanese: 'ドーブル', chinese: '图图犬' },
  { name: 'Tyrogue', id: 236, japanese: 'バルキー', chinese: '无畏小子' },
  { name: 'Hitmontop', id: 237, japanese: 'カポエラー', chinese: '战舞郎' },
  { name: 'Smoochum', id: 238, japanese: 'ムチュール', chinese: '迷唇娃' },
  { name: 'Elekid', id: 239, japanese: 'エレキッド', chinese: '电击怪' },
  { name: 'Magby', id: 240, japanese: 'ブビィ', chinese: '鸭嘴宝宝' },
  { name: 'Miltank', id: 241, japanese: 'ミルタンク', chinese: '大奶罐' },
  { name: 'Blissey', id: 242, japanese: 'ハピナス', chinese: '幸福蛋' },
  { name: 'Raikou', id: 243, japanese: 'ライコウ', chinese: '雷公' },
  { name: 'Entei', id: 244, japanese: 'エンテイ', chinese: '炎帝' },
  { name: 'Suicune', id: 245, japanese: 'スイクン', chinese: '水君' },
  { name: 'Larvitar', id: 246, japanese: 'ヨーギラス', chinese: '幼基拉斯' },
  { name: 'Pupitar', id: 247, japanese: 'サナギラス', chinese: '沙基拉斯' },
  { name: 'Tyranitar', id: 248, japanese: 'バンギラス', chinese: '班基拉斯' },
  { name: 'Lugia', id: 249, japanese: 'ルギア', chinese: '洛奇亚' },
  { name: 'Ho-Oh', id: 250, japanese: 'ホウオウ', chinese: '凤王' },
  { name: 'Celebi', id: 251, japanese: 'セレビィ', chinese: '时拉比' },
  { name: 'Treecko', id: 252, japanese: 'キモリ', chinese: '木守宫' },
  { name: 'Grovyle', id: 253, japanese: 'ジュプトル', chinese: '森林蜥蜴' },
  { name: 'Sceptile', id: 254, japanese: 'ジュカイン', chinese: '蜥蜴王' },
  { name: 'Torchic', id: 255, japanese: 'アチャモ', chinese: '火稚鸡' },
  { name: 'Combusken', id: 256, japanese: 'ワカシャモ', chinese: '力壮鸡' },
  { name: 'Blaziken', id: 257, japanese: 'バシャーモ', chinese: '火焰鸡' },
  { name: 'Mudkip', id: 258, japanese: 'ミズゴロウ', chinese: '水跃鱼' },
  { name: 'Marshtomp', id: 259, japanese: 'ヌマクロー', chinese: '沼跃鱼' },
  { name: 'Swampert', id: 260, japanese: 'ラグラージ', chinese: '巨沼怪' },
  { name: 'Poochyena', id: 261, japanese: 'ポチエナ', chinese: '土狼犬' },
  { name: 'Mightyena', id: 262, japanese: 'グラエナ', chinese: '大狼犬' },
  { name: 'Zigzagoon', id: 263, japanese: 'ジグザグマ', chinese: '蛇纹熊' },
  { name: 'Linoone', id: 264, japanese: 'マッスグマ', chinese: '直冲熊' },
  { name: 'Wurmple', id: 265, japanese: 'ケムッソ', chinese: '刺尾虫' },
  { name: 'Silcoon', id: 266, japanese: 'カラサリス', chinese: '甲壳茧' },
  { name: 'Beautifly', id: 267, japanese: 'アゲハント', chinese: '狩猎凤蝶' },
  { name: 'Cascoon', id: 268, japanese: 'マユルド', chinese: '盾甲茧' },
  { name: 'Dustox', id: 269, japanese: 'ドクケイル', chinese: '毒粉蛾' },
  { name: 'Lotad', id: 270, japanese: 'ハスボー', chinese: '莲叶童子' },
  { name: 'Lombre', id: 271, japanese: 'ハスブレロ', chinese: '莲帽小童' },
  { name: 'Ludicolo', id: 272, japanese: 'ルンパッパ', chinese: '乐天河童' },
  { name: 'Seedot', id: 273, japanese: 'タネボー', chinese: '橡实果' },
  { name: 'Nuzleaf', id: 274, japanese: 'コノハナ', chinese: '长鼻叶' },
  { name: 'Shiftry', id: 275, japanese: 'ダーテング', chinese: '狡猾天狗' },
  { name: 'Taillow', id: 276, japanese: 'スバメ', chinese: '傲骨燕' },
  { name: 'Swellow', id: 277, japanese: 'オオスバメ', chinese: '大王燕' },
  { name: 'Wingull', id: 278, japanese: 'キャモメ', chinese: '长翅鸥' },
  { name: 'Pelipper', id: 279, japanese: 'ペリッパー', chinese: '大嘴鸥' },
  { name: 'Ralts', id: 280, japanese: 'ラルトス', chinese: '拉鲁拉丝' },
  { name: 'Kirlia', id: 281, japanese: 'キルリア', chinese: '奇鲁莉安' },
  { name: 'Gardevoir', id: 282, japanese: 'サーナイト', chinese: '沙奈朵' },
  { name: 'Surskit', id: 283, japanese: 'アメタマ', chinese: '溜溜糖球' },
  { name: 'Masquerain', id: 284, japanese: 'アメモース', chinese: '雨翅蛾' },
  { name: 'Shroomish', id: 285, japanese: 'キノココ', chinese: '蘑蘑菇' },
  { name: 'Breloom', id: 286, japanese: 'キノガッサ', chinese: '斗笠菇' },
  { name: 'Slakoth', id: 287, japanese: 'ナマケロ', chinese: '懒人獭' },
  { name: 'Vigoroth', id: 288, japanese: 'ヤルキモノ', chinese: '过动猿' },
  { name: 'Slaking', id: 289, japanese: 'ケッキング', chinese: '请假王' },
  { name: 'Nincada', id: 290, japanese: 'ツチニン', chinese: '土居忍士' },
  { name: 'Ninjask', id: 291, japanese: 'テッカニン', chinese: '铁面忍者' },
  { name: 'Shedinja', id: 292, japanese: 'ヌケニン', chinese: '脱壳忍者' },
  { name: 'Whismur', id: 293, japanese: 'ゴニョニョ', chinese: '咕妞妞' },
  { name: 'Loudred', id: 294, japanese: 'ドゴーム', chinese: '吼爆弹' },
  { name: 'Exploud', id: 295, japanese: 'バクオング', chinese: '爆音怪' },
  { name: 'Makuhita', id: 296, japanese: 'マクノシタ', chinese: '幕下力士' },
  { name: 'Hariyama', id: 297, japanese: 'ハリテヤマ', chinese: '铁掌力士' },
  { name: 'Azurill', id: 298, japanese: 'ルリリ', chinese: '露力丽' },
  { name: 'Nosepass', id: 299, japanese: 'ノズパス', chinese: '朝北鼻' },
  { name: 'Skitty', id: 300, japanese: 'エネコ', chinese: '向尾喵' },
  { name: 'Delcatty', id: 301, japanese: 'エネコロロ', chinese: '优雅猫' },
  { name: 'Sableye', id: 302, japanese: 'ヤミラミ', chinese: '勾魂眼' },
  { name: 'Mawile', id: 303, japanese: 'クチート', chinese: '大嘴娃' },
  { name: 'Aron', id: 304, japanese: 'ココドラ', chinese: '可可多拉' },
  { name: 'Lairon', id: 305, japanese: 'コドラ', chinese: '可多拉' },
  { name: 'Aggron', id: 306, japanese: 'ボスゴドラ', chinese: '波士可多拉' },
  { name: 'Meditite', id: 307, japanese: 'アサナン', chinese: '玛沙那' },
  { name: 'Medicham', id: 308, japanese: 'チャーレム', chinese: '恰雷姆' },
  { name: 'Electrike', id: 309, japanese: 'ラクライ', chinese: '落雷兽' },
  { name: 'Manectric', id: 310, japanese: 'ライボルト', chinese: '雷电兽' },
  { name: 'Plusle', id: 311, japanese: 'プラスル', chinese: '正电拍拍' },
  { name: 'Minun', id: 312, japanese: 'マイナン', chinese: '负电拍拍' },
  { name: 'Volbeat', id: 313, japanese: 'バルビート', chinese: '电萤虫' },
  { name: 'Illumise', id: 314, japanese: 'イルミーゼ', chinese: '甜甜萤' },
  { name: 'Roselia', id: 315, japanese: 'ロゼリア', chinese: '毒蔷薇' },
  { name: 'Gulpin', id: 316, japanese: 'ゴクリン', chinese: '溶食兽' },
  { name: 'Swalot', id: 317, japanese: 'マルノーム', chinese: '吞食兽' },
  { name: 'Carvanha', id: 318, japanese: 'キバニア', chinese: '利牙鱼' },
  { name: 'Sharpedo', id: 319, japanese: 'サメハダー', chinese: '巨牙鲨' },
  { name: 'Wailmer', id: 320, japanese: 'ホエルコ', chinese: '吼吼鲸' },
  { name: 'Wailord', id: 321, japanese: 'ホエルオー', chinese: '吼鲸王' },
  { name: 'Numel', id: 322, japanese: 'ドンメル', chinese: '呆火驼' },
  { name: 'Camerupt', id: 323, japanese: 'バクーダ', chinese: '喷火驼' },
  { name: 'Torkoal', id: 324, japanese: 'コータス', chinese: '煤炭龟' },
  { name: 'Spoink', id: 325, japanese: 'バネブー', chinese: '跳跳猪' },
  { name: 'Grumpig', id: 326, japanese: 'ブーピッグ', chinese: '噗噗猪' },
  { name: 'Spinda', id: 327, japanese: 'パッチール', chinese: '晃晃斑' },
  { name: 'Trapinch', id: 328, japanese: 'ナックラー', chinese: '大颚蚁' },
  { name: 'Vibrava', id: 329, japanese: 'ビブラーバ', chinese: '超音波幼虫' },
  { name: 'Flygon', id: 330, japanese: 'フライゴン', chinese: '沙漠蜻蜓' },
  { name: 'Cacnea', id: 331, japanese: 'サボネア', chinese: '刺球仙人掌' },
  { name: 'Cacturne', id: 332, japanese: 'ノクタス', chinese: '梦歌仙人掌' },
  { name: 'Swablu', id: 333, japanese: 'チルット', chinese: '青绵鸟' },
  { name: 'Altaria', id: 334, japanese: 'チルタリス', chinese: '七夕青鸟' },
  { name: 'Zangoose', id: 335, japanese: 'ザングース', chinese: '猫鼬斩' },
  { name: 'Seviper', id: 336, japanese: 'ハブネーク', chinese: '饭匙蛇' },
  { name: 'Lunatone', id: 337, japanese: 'ルナトーン', chinese: '月石' },
  { name: 'Solrock', id: 338, japanese: 'ソルロック', chinese: '太阳岩' },
  { name: 'Barboach', id: 339, japanese: 'ドジョッチ', chinese: '泥泥鳅' },
  { name: 'Whiscash', id: 340, japanese: 'ナマズン', chinese: '鲶鱼王' },
  { name: 'Corphish', id: 341, japanese: 'ヘイガニ', chinese: '龙虾小兵' },
  { name: 'Crawdaunt', id: 342, japanese: 'シザリガー', chinese: '铁螯龙虾' },
  { name: 'Baltoy', id: 343, japanese: 'ヤジロン', chinese: '天秤偶' },
  { name: 'Claydol', id: 344, japanese: 'ネンドール', chinese: '念力土偶' },
  { name: 'Lileep', id: 345, japanese: 'リリーラ', chinese: '触手百合' },
  { name: 'Cradily', id: 346, japanese: 'ユレイドル', chinese: '摇篮百合' },
  { name: 'Anorith', id: 347, japanese: 'アノプス', chinese: '太古羽虫' },
  { name: 'Armaldo', id: 348, japanese: 'アーマルド', chinese: '太古盔甲' },
  { name: 'Feebas', id: 349, japanese: 'ヒンバス', chinese: '丑丑鱼' },
  { name: 'Milotic', id: 350, japanese: 'ミロカロス', chinese: '美纳斯' },
  { name: 'Castform', id: 351, japanese: 'ポワルン', chinese: '飘浮泡泡' },
  { name: 'Kecleon', id: 352, japanese: 'カクレオン', chinese: '变隐龙' },
  { name: 'Shuppet', id: 353, japanese: 'カゲボウズ', chinese: '怨影娃娃' },
  { name: 'Banette', id: 354, japanese: 'ジュペッタ', chinese: '诅咒娃娃' },
  { name: 'Duskull', id: 355, japanese: 'ヨマワル', chinese: '夜巡灵' },
  { name: 'Dusclops', id: 356, japanese: 'サマヨール', chinese: '彷徨夜灵' },
  { name: 'Tropius', id: 357, japanese: 'トロピウス', chinese: '热带龙' },
  { name: 'Chimecho', id: 358, japanese: 'チリーン', chinese: '风铃铃' },
  { name: 'Absol', id: 359, japanese: 'アブソル', chinese: '阿勃梭鲁' },
  { name: 'Wynaut', id: 360, japanese: 'ソーナノ', chinese: '小果然' },
  { name: 'Snorunt', id: 361, japanese: 'ユキワラシ', chinese: '雪童子' },
  { name: 'Glalie', id: 362, japanese: 'オニゴーリ', chinese: '冰鬼护' },
  { name: 'Spheal', id: 363, japanese: 'タマザラシ', chinese: '海豹球' },
  { name: 'Sealeo', id: 364, japanese: 'トドグラー', chinese: '海魔狮' },
  { name: 'Walrein', id: 365, japanese: 'トドゼルガ', chinese: '帝牙海狮' },
  { name: 'Clamperl', id: 366, japanese: 'パールル', chinese: '珍珠贝' },
  { name: 'Huntail', id: 367, japanese: 'ハンテール', chinese: '猎斑鱼' },
  { name: 'Gorebyss', id: 368, japanese: 'サクラビス', chinese: '樱花鱼' },
  { name: 'Relicanth', id: 369, japanese: 'ジーランス', chinese: '古空棘鱼' },
  { name: 'Luvdisc', id: 370, japanese: 'ラブカス', chinese: '爱心鱼' },
  { name: 'Bagon', id: 371, japanese: 'タツベイ', chinese: '宝贝龙' },
  { name: 'Shelgon', id: 372, japanese: 'コモルー', chinese: '甲壳龙' },
  { name: 'Salamence', id: 373, japanese: 'ボーマンダ', chinese: '暴飞龙' },
  { name: 'Beldum', id: 374, japanese: 'ダンバル', chinese: '铁哑铃' },
  { name: 'Metang', id: 375, japanese: 'メタング', chinese: '金属怪' },
  { name: 'Metagross', id: 376, japanese: 'メタグロス', chinese: '巨金怪' },
  { name: 'Regirock', id: 377, japanese: 'レジロック', chinese: '雷吉洛克' },
  { name: 'Regice', id: 378, japanese: 'レジアイス', chinese: '雷吉艾斯' },
  { name: 'Registeel', id: 379, japanese: 'レジスチル', chinese: '雷吉斯奇鲁' },
  { name: 'Latias', id: 380, japanese: 'ラティアス', chinese: '拉帝亚斯' },
  { name: 'Latios', id: 381, japanese: 'ラティオス', chinese: '拉帝欧斯' },
  { name: 'Kyogre', id: 382, japanese: 'カイオーガ', chinese: '盖欧卡' },
  { name: 'Groudon', id: 383, japanese: 'グラードン', chinese: '固拉多' },
  { name: 'Rayquaza', id: 384, japanese: 'レックウザ', chinese: '烈空坐' },
  { name: 'Jirachi', id: 385, japanese: 'ジラーチ', chinese: '基拉祈' },
  {
    name: 'Deoxys-Normal',
    id: 386,
    japanese: 'デオキシス',
    chinese: '代欧奇希斯',
  },
  { name: 'Turtwig', id: 387, japanese: 'ナエトル', chinese: '草苗龟' },
  { name: 'Grotle', id: 388, japanese: 'ハヤシガメ', chinese: '树林龟' },
  { name: 'Torterra', id: 389, japanese: 'ドダイトス', chinese: '土台龟' },
  { name: 'Chimchar', id: 390, japanese: 'ヒコザル', chinese: '小火焰猴' },
  { name: 'Monferno', id: 391, japanese: 'モウカザル', chinese: '猛火猴' },
  { name: 'Infernape', id: 392, japanese: 'ゴウカザル', chinese: '烈焰猴' },
  { name: 'Piplup', id: 393, japanese: 'ポッチャマ', chinese: '波加曼' },
  { name: 'Prinplup', id: 394, japanese: 'ポッタイシ', chinese: '波皇子' },
  { name: 'Empoleon', id: 395, japanese: 'エンペルト', chinese: '帝王拿波' },
  { name: 'Starly', id: 396, japanese: 'ムックル', chinese: '姆克儿' },
  { name: 'Staravia', id: 397, japanese: 'ムクバード', chinese: '姆克鸟' },
  { name: 'Staraptor', id: 398, japanese: 'ムクホーク', chinese: '姆克鹰' },
  { name: 'Bidoof', id: 399, japanese: 'ビッパ', chinese: '大牙狸' },
  { name: 'Bibarel', id: 400, japanese: 'ビーダル', chinese: '大尾狸' },
  { name: 'Kricketot', id: 401, japanese: 'コロボーシ', chinese: '圆法师' },
  { name: 'Kricketune', id: 402, japanese: 'コロトック', chinese: '音箱蟀' },
  { name: 'Shinx', id: 403, japanese: 'コリンク', chinese: '小猫怪' },
  { name: 'Luxio', id: 404, japanese: 'ルクシオ', chinese: '勒克猫' },
  { name: 'Luxray', id: 405, japanese: 'レントラー', chinese: '伦琴猫' },
  { name: 'Budew', id: 406, japanese: 'スボミー', chinese: '含羞苞' },
  { name: 'Roserade', id: 407, japanese: 'ロズレイド', chinese: '罗丝雷朵' },
  { name: 'Cranidos', id: 408, japanese: 'ズガイドス', chinese: '头盖龙' },
  { name: 'Rampardos', id: 409, japanese: 'ラムパルド', chinese: '战槌龙' },
  { name: 'Shieldon', id: 410, japanese: 'タテトプス', chinese: '盾甲龙' },
  { name: 'Bastiodon', id: 411, japanese: 'トリデプス', chinese: '护城龙' },
  { name: 'Burmy', id: 412, japanese: 'ミノムッチ', chinese: '结草儿' },
  {
    name: 'Wormadam-Plant',
    id: 413,
    japanese: 'ミノマダム',
    chinese: '结草贵妇',
  },
  { name: 'Mothim', id: 414, japanese: 'ガーメイル', chinese: '绅士蛾' },
  { name: 'Combee', id: 415, japanese: 'ミツハニー', chinese: '三蜜蜂' },
  { name: 'Vespiquen', id: 416, japanese: 'ビークイン', chinese: '蜂女王' },
  { name: 'Pachirisu', id: 417, japanese: 'パチリス', chinese: '帕奇利兹' },
  { name: 'Buizel', id: 418, japanese: 'ブイゼル', chinese: '泳圈鼬' },
  { name: 'Floatzel', id: 419, japanese: 'フローゼル', chinese: '浮潜鼬' },
  { name: 'Cherubi', id: 420, japanese: 'チェリンボ', chinese: '樱花宝' },
  { name: 'Cherrim', id: 421, japanese: 'チェリム', chinese: '樱花儿' },
  { name: 'Shellos', id: 422, japanese: 'カラナクシ', chinese: '无壳海兔' },
  { name: 'Gastrodon', id: 423, japanese: 'トリトドン', chinese: '海兔兽' },
  { name: 'Ambipom', id: 424, japanese: 'エテボース', chinese: '双尾怪手' },
  { name: 'Drifloon', id: 425, japanese: 'フワンテ', chinese: '飘飘球' },
  { name: 'Drifblim', id: 426, japanese: 'フワライド', chinese: '随风球' },
  { name: 'Buneary', id: 427, japanese: 'ミミロル', chinese: '卷卷耳' },
  { name: 'Lopunny', id: 428, japanese: 'ミミロップ', chinese: '长耳兔' },
  { name: 'Mismagius', id: 429, japanese: 'ムウマージ', chinese: '梦妖魔' },
  { name: 'Honchkrow', id: 430, japanese: 'ドンカラス', chinese: '乌鸦头头' },
  { name: 'Glameow', id: 431, japanese: 'ニャルマー', chinese: '魅力喵' },
  { name: 'Purugly', id: 432, japanese: 'ブニャット', chinese: '东施喵' },
  { name: 'Chingling', id: 433, japanese: 'リーシャン', chinese: '铃铛响' },
  { name: 'Stunky', id: 434, japanese: 'スカンプー', chinese: '臭鼬噗' },
  { name: 'Skuntank', id: 435, japanese: 'スカタンク', chinese: '坦克臭鼬' },
  { name: 'Bronzor', id: 436, japanese: 'ドーミラー', chinese: '铜镜怪' },
  { name: 'Bronzong', id: 437, japanese: 'ドータクン', chinese: '青铜钟' },
  { name: 'Bonsly', id: 438, japanese: 'ウソハチ', chinese: '盆才怪' },
  { name: 'Mime-Jr', id: 439, japanese: 'マネネ', chinese: '魔尼尼' },
  { name: 'Happiny', id: 440, japanese: 'ピンプク', chinese: '小福蛋' },
  { name: 'Chatot', id: 441, japanese: 'ペラップ', chinese: '聒噪鸟' },
  { name: 'Spiritomb', id: 442, japanese: 'ミカルゲ', chinese: '花岩怪' },
  { name: 'Gible', id: 443, japanese: 'フカマル', chinese: '圆陆鲨' },
  { name: 'Gabite', id: 444, japanese: 'ガバイト', chinese: '尖牙陆鲨' },
  { name: 'Garchomp', id: 445, japanese: 'ガブリアス', chinese: '烈咬陆鲨' },
  { name: 'Munchlax', id: 446, japanese: 'ゴンベ', chinese: '小卡比兽' },
  { name: 'Riolu', id: 447, japanese: 'リオル', chinese: '利欧路' },
  { name: 'Lucario', id: 448, japanese: 'ルカリオ', chinese: '路卡利欧' },
  { name: 'Hippopotas', id: 449, japanese: 'ヒポポタス', chinese: '沙河马' },
  { name: 'Hippowdon', id: 450, japanese: 'カバルドン', chinese: '河马兽' },
  { name: 'Skorupi', id: 451, japanese: 'スコルピ', chinese: '钳尾蝎' },
  { name: 'Drapion', id: 452, japanese: 'ドラピオン', chinese: '龙王蝎' },
  { name: 'Croagunk', id: 453, japanese: 'グレッグル', chinese: '不良蛙' },
  { name: 'Toxicroak', id: 454, japanese: 'ドクロッグ', chinese: '毒骷蛙' },
  { name: 'Carnivine', id: 455, japanese: 'マスキッパ', chinese: '尖牙笼' },
  { name: 'Finneon', id: 456, japanese: 'ケイコウオ', chinese: '荧光鱼' },
  { name: 'Lumineon', id: 457, japanese: 'ネオラント', chinese: '霓虹鱼' },
  { name: 'Mantyke', id: 458, japanese: 'タマンタ', chinese: '小球飞鱼' },
  { name: 'Snover', id: 459, japanese: 'ユキカブリ', chinese: '雪笠怪' },
  { name: 'Abomasnow', id: 460, japanese: 'ユキノオー', chinese: '暴雪王' },
  { name: 'Weavile', id: 461, japanese: 'マニューラ', chinese: '玛狃拉' },
  { name: 'Magnezone', id: 462, japanese: 'ジバコイル', chinese: '自爆磁怪' },
  { name: 'Lickilicky', id: 463, japanese: 'ベロベルト', chinese: '大舌舔' },
  { name: 'Rhyperior', id: 464, japanese: 'ドサイドン', chinese: '超甲狂犀' },
  { name: 'Tangrowth', id: 465, japanese: 'モジャンボ', chinese: '巨蔓藤' },
  { name: 'Electivire', id: 466, japanese: 'エレキブル', chinese: '电击魔兽' },
  { name: 'Magmortar', id: 467, japanese: 'ブーバーン', chinese: '鸭嘴炎兽' },
  { name: 'Togekiss', id: 468, japanese: 'トゲキッス', chinese: '波克基斯' },
  { name: 'Yanmega', id: 469, japanese: 'メガヤンマ', chinese: '远古巨蜓' },
  { name: 'Leafeon', id: 470, japanese: 'リーフィア', chinese: '叶伊布' },
  { name: 'Glaceon', id: 471, japanese: 'グレイシア', chinese: '冰伊布' },
  { name: 'Gliscor', id: 472, japanese: 'グライオン', chinese: '天蝎王' },
  { name: 'Mamoswine', id: 473, japanese: 'マンムー', chinese: '象牙猪' },
  { name: 'Porygon-Z', id: 474, japanese: 'ポリゴンＺ', chinese: '多边兽Ｚ' },
  { name: 'Gallade', id: 475, japanese: 'エルレイド', chinese: '艾路雷朵' },
  { name: 'Probopass', id: 476, japanese: 'ダイノーズ', chinese: '大朝北鼻' },
  { name: 'Dusknoir', id: 477, japanese: 'ヨノワール', chinese: '黑夜魔灵' },
  { name: 'Froslass', id: 478, japanese: 'ユキメノコ', chinese: '雪妖女' },
  { name: 'Rotom', id: 479, japanese: 'ロトム', chinese: '洛托姆' },
  { name: 'Uxie', id: 480, japanese: 'ユクシー', chinese: '由克希' },
  { name: 'Mesprit', id: 481, japanese: 'エムリット', chinese: '艾姆利多' },
  { name: 'Azelf', id: 482, japanese: 'アグノム', chinese: '亚克诺姆' },
  { name: 'Dialga', id: 483, japanese: 'ディアルガ', chinese: '帝牙卢卡' },
  { name: 'Palkia', id: 484, japanese: 'パルキア', chinese: '帕路奇亚' },
  { name: 'Heatran', id: 485, japanese: 'ヒードラン', chinese: '席多蓝恩' },
  { name: 'Regigigas', id: 486, japanese: 'レジギガス', chinese: '雷吉奇卡斯' },
  {
    name: 'Giratina-Altered',
    id: 487,
    japanese: 'ギラティナ',
    chinese: '骑拉帝纳',
  },
  { name: 'Cresselia', id: 488, japanese: 'クレセリア', chinese: '克雷色利亚' },
  { name: 'Phione', id: 489, japanese: 'フィオネ', chinese: '霏欧纳' },
  { name: 'Manaphy', id: 490, japanese: 'マナフィ', chinese: '玛纳霏' },
  { name: 'Darkrai', id: 491, japanese: 'ダークライ', chinese: '达克莱伊' },
  { name: 'Shaymin-Land', id: 492, japanese: 'シェイミ', chinese: '谢米' },
  { name: 'Arceus', id: 493, japanese: 'アルセウス', chinese: '阿尔宙斯' },
  { name: 'Victini', id: 494, japanese: 'ビクティニ', chinese: '比克提尼' },
  { name: 'Snivy', id: 495, japanese: 'ツタージャ', chinese: '藤藤蛇' },
  { name: 'Servine', id: 496, japanese: 'ジャノビー', chinese: '青藤蛇' },
  { name: 'Serperior', id: 497, japanese: 'ジャローダ', chinese: '君主蛇' },
  { name: 'Tepig', id: 498, japanese: 'ポカブ', chinese: '暖暖猪' },
  { name: 'Pignite', id: 499, japanese: 'チャオブー', chinese: '炒炒猪' },
  { name: 'Emboar', id: 500, japanese: 'エンブオー', chinese: '炎武王' },
  { name: 'Oshawott', id: 501, japanese: 'ミジュマル', chinese: '水水獭' },
  { name: 'Dewott', id: 502, japanese: 'フタチマル', chinese: '双刃丸' },
  { name: 'Samurott', id: 503, japanese: 'ダイケンキ', chinese: '大剑鬼' },
  { name: 'Patrat', id: 504, japanese: 'ミネズミ', chinese: '探探鼠' },
  { name: 'Watchog', id: 505, japanese: 'ミルホッグ', chinese: '步哨鼠' },
  { name: 'Lillipup', id: 506, japanese: 'ヨーテリー', chinese: '小约克' },
  { name: 'Herdier', id: 507, japanese: 'ハーデリア', chinese: '哈约克' },
  { name: 'Stoutland', id: 508, japanese: 'ムーランド', chinese: '长毛狗' },
  { name: 'Purrloin', id: 509, japanese: 'チョロネコ', chinese: '扒手猫' },
  { name: 'Liepard', id: 510, japanese: 'レパルダス', chinese: '酷豹' },
  { name: 'Pansage', id: 511, japanese: 'ヤナップ', chinese: '花椰猴' },
  { name: 'Simisage', id: 512, japanese: 'ヤナッキー', chinese: '花椰猿' },
  { name: 'Pansear', id: 513, japanese: 'バオップ', chinese: '爆香猴' },
  { name: 'Simisear', id: 514, japanese: 'バオッキー', chinese: '爆香猿' },
  { name: 'Panpour', id: 515, japanese: 'ヒヤップ', chinese: '冷水猴' },
  { name: 'Simipour', id: 516, japanese: 'ヒヤッキー', chinese: '冷水猿' },
  { name: 'Munna', id: 517, japanese: 'ムンナ', chinese: '食梦梦' },
  { name: 'Musharna', id: 518, japanese: 'ムシャーナ', chinese: '梦梦蚀' },
  { name: 'Pidove', id: 519, japanese: 'マメパト', chinese: '豆豆鸽' },
  { name: 'Tranquill', id: 520, japanese: 'ハトーボー', chinese: '咕咕鸽' },
  { name: 'Unfezant', id: 521, japanese: 'ケンホロウ', chinese: '高傲雉鸡' },
  { name: 'Blitzle', id: 522, japanese: 'シママ', chinese: '斑斑马' },
  { name: 'Zebstrika', id: 523, japanese: 'ゼブライカ', chinese: '雷电斑马' },
  { name: 'Roggenrola', id: 524, japanese: 'ダンゴロ', chinese: '石丸子' },
  { name: 'Boldore', id: 525, japanese: 'ガントル', chinese: '地幔岩' },
  { name: 'Gigalith', id: 526, japanese: 'ギガイアス', chinese: '庞岩怪' },
  { name: 'Woobat', id: 527, japanese: 'コロモリ', chinese: '滚滚蝙蝠' },
  { name: 'Swoobat', id: 528, japanese: 'ココロモリ', chinese: '心蝙蝠' },
  { name: 'Drilbur', id: 529, japanese: 'モグリュー', chinese: '螺钉地鼠' },
  { name: 'Excadrill', id: 530, japanese: 'ドリュウズ', chinese: '龙头地鼠' },
  { name: 'Audino', id: 531, japanese: 'タブンネ', chinese: '差不多娃娃' },
  { name: 'Timburr', id: 532, japanese: 'ドッコラー', chinese: '搬运小匠' },
  { name: 'Gurdurr', id: 533, japanese: 'ドテッコツ', chinese: '铁骨土人' },
  { name: 'Conkeldurr', id: 534, japanese: 'ローブシン', chinese: '修建老匠' },
  { name: 'Tympole', id: 535, japanese: 'オタマロ', chinese: '圆蝌蚪' },
  { name: 'Palpitoad', id: 536, japanese: 'ガマガル', chinese: '蓝蟾蜍' },
  { name: 'Seismitoad', id: 537, japanese: 'ガマゲロゲ', chinese: '蟾蜍王' },
  { name: 'Throh', id: 538, japanese: 'ナゲキ', chinese: '投摔鬼' },
  { name: 'Sawk', id: 539, japanese: 'ダゲキ', chinese: '打击鬼' },
  { name: 'Sewaddle', id: 540, japanese: 'クルミル', chinese: '虫宝包' },
  { name: 'Swadloon', id: 541, japanese: 'クルマユ', chinese: '宝包茧' },
  { name: 'Leavanny', id: 542, japanese: 'ハハコモリ', chinese: '保姆虫' },
  { name: 'Venipede', id: 543, japanese: 'フシデ', chinese: '百足蜈蚣' },
  { name: 'Whirlipede', id: 544, japanese: 'ホイーガ', chinese: '车轮球' },
  { name: 'Scolipede', id: 545, japanese: 'ペンドラー', chinese: '蜈蚣王' },
  { name: 'Cottonee', id: 546, japanese: 'モンメン', chinese: '木棉球' },
  { name: 'Whimsicott', id: 547, japanese: 'エルフーン', chinese: '风妖精' },
  { name: 'Petilil', id: 548, japanese: 'チュリネ', chinese: '百合根娃娃' },
  { name: 'Lilligant', id: 549, japanese: 'ドレディア', chinese: '裙儿小姐' },
  { name: 'Basculin-Red-Striped', id: 550, japanese: 'バスラオ', chinese: '野蛮鲈鱼' },
  { name: 'Sandile', id: 551, japanese: 'メグロコ', chinese: '黑眼鳄' },
  { name: 'Krokorok', id: 552, japanese: 'ワルビル', chinese: '混混鳄' },
  { name: 'Krookodile', id: 553, japanese: 'ワルビアル', chinese: '流氓鳄' },
  { name: 'Darumaka', id: 554, japanese: 'ダルマッカ', chinese: '火红不倒翁' },
  { name: 'Darmanitan-Standard', id: 555, japanese: 'ヒヒダルマ', chinese: '达摩狒狒' },
  { name: 'Maractus', id: 556, japanese: 'マラカッチ', chinese: '沙铃仙人掌' },
  { name: 'Dwebble', id: 557, japanese: 'イシズマイ', chinese: '石居蟹' },
  { name: 'Crustle', id: 558, japanese: 'イワパレス', chinese: '岩殿居蟹' },
  { name: 'Scraggy', id: 559, japanese: 'ズルッグ', chinese: '滑滑小子' },
  { name: 'Scrafty', id: 560, japanese: 'ズルズキン', chinese: '头巾混混' },
  { name: 'Sigilyph', id: 561, japanese: 'シンボラー', chinese: '象征鸟' },
  { name: 'Yamask', id: 562, japanese: 'デスマス', chinese: '哭哭面具' },
  { name: 'Cofagrigus', id: 563, japanese: 'デスカーン', chinese: '迭失棺' },
  { name: 'Tirtouga', id: 564, japanese: 'プロトーガ', chinese: '原盖海龟' },
  { name: 'Carracosta', id: 565, japanese: 'アバゴーラ', chinese: '肋骨海龟' },
  { name: 'Archen', id: 566, japanese: 'アーケン', chinese: '始祖小鸟' },
  { name: 'Archeops', id: 567, japanese: 'アーケオス', chinese: '始祖大鸟' },
  { name: 'Trubbish', id: 568, japanese: 'ヤブクロン', chinese: '破破袋' },
  { name: 'Garbodor', id: 569, japanese: 'ダストダス', chinese: '灰尘山' },
  { name: 'Zorua', id: 570, japanese: 'ゾロア', chinese: '索罗亚' },
  { name: 'Zoroark', id: 571, japanese: 'ゾロアーク', chinese: '索罗亚克' },
  { name: 'Minccino', id: 572, japanese: 'チラーミィ', chinese: '泡沫栗鼠' },
  { name: 'Cinccino', id: 573, japanese: 'チラチーノ', chinese: '奇诺栗鼠' },
  { name: 'Gothita', id: 574, japanese: 'ゴチム', chinese: '哥德宝宝' },
  { name: 'Gothorita', id: 575, japanese: 'ゴチミル', chinese: '哥德小童' },
  { name: 'Gothitelle', id: 576, japanese: 'ゴチルゼル', chinese: '哥德小姐' },
  { name: 'Solosis', id: 577, japanese: 'ユニラン', chinese: '单卵细胞球' },
  { name: 'Duosion', id: 578, japanese: 'ダブラン', chinese: '双卵细胞球' },
  { name: 'Reuniclus', id: 579, japanese: 'ランクルス', chinese: '人造细胞卵' },
  { name: 'Ducklett', id: 580, japanese: 'コアルヒー', chinese: '鸭宝宝' },
  { name: 'Swanna', id: 581, japanese: 'スワンナ', chinese: '舞天鹅' },
  { name: 'Vanillite', id: 582, japanese: 'バニプッチ', chinese: '迷你冰' },
  { name: 'Vanillish', id: 583, japanese: 'バニリッチ', chinese: '多多冰' },
  { name: 'Vanilluxe', id: 584, japanese: 'バイバニラ', chinese: '双倍多多冰' },
  { name: 'Deerling', id: 585, japanese: 'シキジカ', chinese: '四季鹿' },
  { name: 'Sawsbuck', id: 586, japanese: 'メブキジカ', chinese: '萌芽鹿' },
  { name: 'Emolga', id: 587, japanese: 'エモンガ', chinese: '电飞鼠' },
  { name: 'Karrablast', id: 588, japanese: 'カブルモ', chinese: '盖盖虫' },
  { name: 'Escavalier', id: 589, japanese: 'シュバルゴ', chinese: '骑士蜗牛' },
  { name: 'Foongus', id: 590, japanese: 'タマゲタケ', chinese: '哎呀球菇' },
  { name: 'Amoonguss', id: 591, japanese: 'モロバレル', chinese: '败露球菇' },
  { name: 'Frillish', id: 592, japanese: 'プルリル', chinese: '轻飘飘' },
  { name: 'Jellicent', id: 593, japanese: 'ブルンゲル', chinese: '胖嘟嘟' },
  { name: 'Alomomola', id: 594, japanese: 'ママンボウ', chinese: '保姆曼波' },
  { name: 'Joltik', id: 595, japanese: 'バチュル', chinese: '电电虫' },
  { name: 'Galvantula', id: 596, japanese: 'デンチュラ', chinese: '电蜘蛛' },
  { name: 'Ferroseed', id: 597, japanese: 'テッシード', chinese: '种子铁球' },
  { name: 'Ferrothorn', id: 598, japanese: 'ナットレイ', chinese: '坚果哑铃' },
  { name: 'Klink', id: 599, japanese: 'ギアル', chinese: '齿轮儿' },
  { name: 'Klang', id: 600, japanese: 'ギギアル', chinese: '齿轮组' },
  { name: 'Klinklang', id: 601, japanese: 'ギギギアル', chinese: '齿轮怪' },
  { name: 'Tynamo', id: 602, japanese: 'シビシラス', chinese: '麻麻小鱼' },
  { name: 'Eelektrik', id: 603, japanese: 'シビビール', chinese: '麻麻鳗' },
  {
    name: 'Eelektross',
    id: 604,
    japanese: 'シビルドン',
    chinese: '麻麻鳗鱼王',
  },
  { name: 'Elgyem', id: 605, japanese: 'リグレー', chinese: '小灰怪' },
  { name: 'Beheeyem', id: 606, japanese: 'オーベム', chinese: '大宇怪' },
  { name: 'Litwick', id: 607, japanese: 'ヒトモシ', chinese: '烛光灵' },
  { name: 'Lampent', id: 608, japanese: 'ランプラー', chinese: '灯火幽灵' },
  {
    name: 'Chandelure',
    id: 609,
    japanese: 'シャンデラ',
    chinese: '水晶灯火灵',
  },
  { name: 'Axew', id: 610, japanese: 'キバゴ', chinese: '牙牙' },
  { name: 'Fraxure', id: 611, japanese: 'オノンド', chinese: '斧牙龙' },
  { name: 'Haxorus', id: 612, japanese: 'オノノクス', chinese: '双斧战龙' },
  { name: 'Cubchoo', id: 613, japanese: 'クマシュン', chinese: '喷嚏熊' },
  { name: 'Beartic', id: 614, japanese: 'ツンベアー', chinese: '冻原熊' },
  { name: 'Cryogonal', id: 615, japanese: 'フリージオ', chinese: '几何雪花' },
  { name: 'Shelmet', id: 616, japanese: 'チョボマキ', chinese: '小嘴蜗' },
  { name: 'Accelgor', id: 617, japanese: 'アギルダー', chinese: '敏捷虫' },
  { name: 'Stunfisk', id: 618, japanese: 'マッギョ', chinese: '泥巴鱼' },
  { name: 'Mienfoo', id: 619, japanese: 'コジョフー', chinese: '功夫鼬' },
  { name: 'Mienshao', id: 620, japanese: 'コジョンド', chinese: '师父鼬' },
  { name: 'Druddigon', id: 621, japanese: 'クリムガン', chinese: '赤面龙' },
  { name: 'Golett', id: 622, japanese: 'ゴビット', chinese: '泥偶小人' },
  { name: 'Golurk', id: 623, japanese: 'ゴルーグ', chinese: '泥偶巨人' },
  { name: 'Pawniard', id: 624, japanese: 'コマタナ', chinese: '驹刀小兵' },
  { name: 'Bisharp', id: 625, japanese: 'キリキザン', chinese: '劈斩司令' },
  {
    name: 'Bouffalant',
    id: 626,
    japanese: 'バッフロン',
    chinese: '爆炸头水牛',
  },
  { name: 'Rufflet', id: 627, japanese: 'ワシボン', chinese: '毛头小鹰' },
  { name: 'Braviary', id: 628, japanese: 'ウォーグル', chinese: '勇士雄鹰' },
  { name: 'Vullaby', id: 629, japanese: 'バルチャイ', chinese: '秃鹰丫头' },
  { name: 'Mandibuzz', id: 630, japanese: 'バルジーナ', chinese: '秃鹰娜' },
  { name: 'Heatmor', id: 631, japanese: 'クイタラン', chinese: '熔蚁兽' },
  { name: 'Durant', id: 632, japanese: 'アイアント', chinese: '铁蚁' },
  { name: 'Deino', id: 633, japanese: 'モノズ', chinese: '单首龙' },
  { name: 'Zweilous', id: 634, japanese: 'ジヘッド', chinese: '双首暴龙' },
  { name: 'Hydreigon', id: 635, japanese: 'サザンドラ', chinese: '三首恶龙' },
  { name: 'Larvesta', id: 636, japanese: 'メラルバ', chinese: '燃烧虫' },
  { name: 'Volcarona', id: 637, japanese: 'ウルガモス', chinese: '火神蛾' },
  { name: 'Cobalion', id: 638, japanese: 'コバルオン', chinese: '勾帕路翁' },
  { name: 'Terrakion', id: 639, japanese: 'テラキオン', chinese: '代拉基翁' },
  { name: 'Virizion', id: 640, japanese: 'ビリジオン', chinese: '毕力吉翁' },
  { name: 'Tornadus-Incarnate', id: 641, japanese: 'トルネロス', chinese: '龙卷云' },
  { name: 'Thundurus-Incarnate', id: 642, japanese: 'ボルトロス', chinese: '雷电云' },
  { name: 'Reshiram', id: 643, japanese: 'レシラム', chinese: '莱希拉姆' },
  { name: 'Zekrom', id: 644, japanese: 'ゼクロム', chinese: '捷克罗姆' },
  { name: 'Landorus-Incarnate', id: 645, japanese: 'ランドロス', chinese: '土地云' },
  { name: 'Kyurem', id: 646, japanese: 'キュレム', chinese: '酋雷姆' },
  { name: 'Keldeo-Ordinary', id: 647, japanese: 'ケルディオ', chinese: '凯路迪欧' },
  { name: 'Meloetta-Aria', id: 648, japanese: 'メロエッタ', chinese: '美洛耶塔' },
  { name: 'Genesect', id: 649, japanese: 'ゲノセクト', chinese: '盖诺赛克特' },
  { name: 'Chespin', id: 650, japanese: 'ハリマロン', chinese: '哈力栗' },
  { name: 'Quilladin', id: 651, japanese: 'ハリボーグ', chinese: '胖胖哈力' },
  { name: 'Chesnaught', id: 652, japanese: 'ブリガロン', chinese: '布里卡隆' },
  { name: 'Fennekin', id: 653, japanese: 'フォッコ', chinese: '火狐狸' },
  { name: 'Braixen', id: 654, japanese: 'テールナー', chinese: '长尾火狐' },
  { name: 'Delphox', id: 655, japanese: 'マフォクシー', chinese: '妖火红狐' },
  { name: 'Froakie', id: 656, japanese: 'ケロマツ', chinese: '呱呱泡蛙' },
  { name: 'Frogadier', id: 657, japanese: 'ゲコガシラ', chinese: '呱头蛙' },
  { name: 'Greninja', id: 658, japanese: 'ゲッコウガ', chinese: '甲贺忍蛙' },
  { name: 'Bunnelby', id: 659, japanese: 'ホルビー', chinese: '掘掘兔' },
  { name: 'Diggersby', id: 660, japanese: 'ホルード', chinese: '掘地兔' },
  { name: 'Fletchling', id: 661, japanese: 'ヤヤコマ', chinese: '小箭雀' },
  { name: 'Fletchinder', id: 662, japanese: 'ヒノヤコマ', chinese: '火箭雀' },
  { name: 'Talonflame', id: 663, japanese: 'ファイアロー', chinese: '烈箭鹰' },
  { name: 'Scatterbug', id: 664, japanese: 'コフキムシ', chinese: '粉蝶虫' },
  { name: 'Spewpa', id: 665, japanese: 'コフーライ', chinese: '粉蝶蛹' },
  { name: 'Vivillon', id: 666, japanese: 'ビビヨン', chinese: '彩粉蝶' },
  { name: 'Litleo', id: 667, japanese: 'シシコ', chinese: '小狮狮' },
  { name: 'Pyroar', id: 668, japanese: 'カエンジシ', chinese: '火炎狮' },
  { name: 'Flabébé', id: 669, japanese: 'フラベベ', chinese: '花蓓蓓' },
  { name: 'Floette', id: 670, japanese: 'フラエッテ', chinese: '花叶蒂' },
  { name: 'Florges', id: 671, japanese: 'フラージェス', chinese: '花洁夫人' },
  { name: 'Skiddo', id: 672, japanese: 'メェークル', chinese: '坐骑小羊' },
  { name: 'Gogoat', id: 673, japanese: 'ゴーゴート', chinese: '坐骑山羊' },
  { name: 'Pancham', id: 674, japanese: 'ヤンチャム', chinese: '顽皮熊猫' },
  { name: 'Pangoro', id: 675, japanese: 'ゴロンダ', chinese: '霸道熊猫' },
  { name: 'Furfrou', id: 676, japanese: 'トリミアン', chinese: '多丽米亚' },
  { name: 'Espurr', id: 677, japanese: 'ニャスパー', chinese: '妙喵' },
  { name: 'Meowstic-Male', id: 678, japanese: 'ニャオニクス', chinese: '超能妙喵' },
  { name: 'Honedge', id: 679, japanese: 'ヒトツキ', chinese: '独剑鞘' },
  { name: 'Doublade', id: 680, japanese: 'ニダンギル', chinese: '双剑鞘' },
  { name: 'Aegislash', id: 681, japanese: 'ギルガルド', chinese: '坚盾剑怪' },
  { name: 'Spritzee', id: 682, japanese: 'シュシュプ', chinese: '粉香香' },
  { name: 'Aromatisse', id: 683, japanese: 'フレフワン', chinese: '芳香精' },
  { name: 'Swirlix', id: 684, japanese: 'ペロッパフ', chinese: '绵绵泡芙' },
  { name: 'Slurpuff', id: 685, japanese: 'ペロリーム', chinese: '胖甜妮' },
  { name: 'Inkay', id: 686, japanese: 'マーイーカ', chinese: '好啦鱿' },
  { name: 'Malamar', id: 687, japanese: 'カラマネロ', chinese: '乌贼王' },
  { name: 'Binacle', id: 688, japanese: 'カメテテ', chinese: '龟脚脚' },
  { name: 'Barbaracle', id: 689, japanese: 'ガメノデス', chinese: '龟足巨铠' },
  { name: 'Skrelp', id: 690, japanese: 'クズモー', chinese: '垃垃藻' },
  { name: 'Dragalge', id: 691, japanese: 'ドラミドロ', chinese: '毒藻龙' },
  { name: 'Clauncher', id: 692, japanese: 'ウデッポウ', chinese: '铁臂枪虾' },
  { name: 'Clawitzer', id: 693, japanese: 'ブロスター', chinese: '钢炮臂虾' },
  { name: 'Helioptile', id: 694, japanese: 'エリキテル', chinese: '伞电蜥' },
  { name: 'Heliolisk', id: 695, japanese: 'エレザード', chinese: '光电伞蜥' },
  { name: 'Tyrunt', id: 696, japanese: 'チゴラス', chinese: '宝宝暴龙' },
  { name: 'Tyrantrum', id: 697, japanese: 'ガチゴラス', chinese: '怪颚龙' },
  { name: 'Amaura', id: 698, japanese: 'アマルス', chinese: '冰雪龙' },
  { name: 'Aurorus', id: 699, japanese: 'アマルルガ', chinese: '冰雪巨龙' },
  { name: 'Sylveon', id: 700, japanese: 'ニンフィア', chinese: '仙子伊布' },
  { name: 'Hawlucha', id: 701, japanese: 'ルチャブル', chinese: '摔角鹰人' },
  { name: 'Dedenne', id: 702, japanese: 'デデンネ', chinese: '咚咚鼠' },
  { name: 'Carbink', id: 703, japanese: 'メレシー', chinese: '小碎钻' },
  { name: 'Goomy', id: 704, japanese: 'ヌメラ', chinese: '黏黏宝' },
  { name: 'Sliggoo', id: 705, japanese: 'ヌメイル', chinese: '黏美儿' },
  { name: 'Goodra', id: 706, japanese: 'ヌメルゴン', chinese: '黏美龙' },
  { name: 'Klefki', id: 707, japanese: 'クレッフィ', chinese: '钥圈儿' },
  { name: 'Phantump', id: 708, japanese: 'ボクレー', chinese: '小木灵' },
  { name: 'Trevenant', id: 709, japanese: 'オーロット', chinese: '朽木妖' },
  { name: 'Pumpkaboo-Average', id: 710, japanese: 'バケッチャ', chinese: '南瓜精' },
  { name: 'Gourgeist-Average', id: 711, japanese: 'パンプジン', chinese: '南瓜怪人' },
  { name: 'Bergmite', id: 712, japanese: 'カチコール', chinese: '冰宝' },
  { name: 'Avalugg', id: 713, japanese: 'クレベース', chinese: '冰岩怪' },
  { name: 'Noibat', id: 714, japanese: 'オンバット', chinese: '嗡蝠' },
  { name: 'Noivern', id: 715, japanese: 'オンバーン', chinese: '音波龙' },
  { name: 'Xerneas', id: 716, japanese: 'ゼルネアス', chinese: '哲尔尼亚斯' },
  { name: 'Yveltal', id: 717, japanese: 'イベルタル', chinese: '伊裴尔塔尔' },
  { name: 'Zygarde-50', id: 718, japanese: 'ジガルデ', chinese: '基格尔德' },
  { name: 'Diancie', id: 719, japanese: 'ディアンシー', chinese: '蒂安希' },
  { name: 'Hoopa', id: 720, japanese: 'フーパ', chinese: '胡帕' },
  {
    name: 'Volcanion',
    id: 721,
    japanese: 'ボルケニオン',
    chinese: '波尔凯尼恩',
  },
  { name: 'Rowlet', id: 722, japanese: 'モクロー', chinese: '木木枭' },
  { name: 'Dartrix', id: 723, japanese: 'フクスロー', chinese: '投羽枭' },
  { name: 'Decidueye', id: 724, japanese: 'ジュナイパー', chinese: '狙射树枭' },
  { name: 'Litten', id: 725, japanese: 'ニャビー', chinese: '火斑喵' },
  { name: 'Torracat', id: 726, japanese: 'ニャヒート', chinese: '炎热喵' },
  {
    name: 'Incineroar',
    id: 727,
    japanese: 'ガオガエン',
    chinese: '炽焰咆哮虎',
  },
  { name: 'Popplio', id: 728, japanese: 'アシマリ', chinese: '球球海狮' },
  { name: 'Brionne', id: 729, japanese: 'オシャマリ', chinese: '花漾海狮' },
  { name: 'Primarina', id: 730, japanese: 'アシレーヌ', chinese: '西狮海壬' },
  { name: 'Pikipek', id: 731, japanese: 'ツツケラ', chinese: '小笃儿' },
  { name: 'Trumbeak', id: 732, japanese: 'ケララッパ', chinese: '喇叭啄鸟' },
  { name: 'Toucannon', id: 733, japanese: 'ドデカバシ', chinese: '铳嘴大鸟' },
  { name: 'Yungoos', id: 734, japanese: 'ヤングース', chinese: '猫鼬少' },
  { name: 'Gumshoos', id: 735, japanese: 'デカグース', chinese: '猫鼬探长' },
  { name: 'Grubbin', id: 736, japanese: 'アゴジムシ', chinese: '强颚鸡母虫' },
  { name: 'Charjabug', id: 737, japanese: 'デンヂムシ', chinese: '虫电宝' },
  { name: 'Vikavolt', id: 738, japanese: 'クワガノン', chinese: '锹农炮虫' },
  { name: 'Crabrawler', id: 739, japanese: 'マケンカニ', chinese: '好胜蟹' },
  {
    name: 'Crabominable',
    id: 740,
    japanese: 'ケケンカニ',
    chinese: '好胜毛蟹',
  },
  { name: 'Oricorio-Baile', id: 741, japanese: 'オドリドリ', chinese: '花舞鸟' },
  { name: 'Cutiefly', id: 742, japanese: 'アブリー', chinese: '萌虻' },
  { name: 'Ribombee', id: 743, japanese: 'アブリボン', chinese: '蝶结萌虻' },
  { name: 'Rockruff', id: 744, japanese: 'イワンコ', chinese: '岩狗狗' },
  { name: 'Lycanroc-Midday', id: 745, japanese: 'ルガルガン', chinese: '鬃岩狼人' },
  { name: 'Wishiwashi-Solo', id: 746, japanese: 'ヨワシ', chinese: '弱丁鱼' },
  { name: 'Mareanie', id: 747, japanese: 'ヒドイデ', chinese: '好坏星' },
  { name: 'Toxapex', id: 748, japanese: 'ドヒドイデ', chinese: '超坏星' },
  { name: 'Mudbray', id: 749, japanese: 'ドロバンコ', chinese: '泥驴仔' },
  { name: 'Mudsdale', id: 750, japanese: 'バンバドロ', chinese: '重泥挽马' },
  { name: 'Dewpider', id: 751, japanese: 'シズクモ', chinese: '滴蛛' },
  { name: 'Araquanid', id: 752, japanese: 'オニシズクモ', chinese: '滴蛛霸' },
  { name: 'Fomantis', id: 753, japanese: 'カリキリ', chinese: '伪螳草' },
  { name: 'Lurantis', id: 754, japanese: 'ラランテス', chinese: '兰螳花' },
  { name: 'Morelull', id: 755, japanese: 'ネマシュ', chinese: '睡睡菇' },
  { name: 'Shiinotic', id: 756, japanese: 'マシェード', chinese: '灯罩夜菇' },
  { name: 'Salandit', id: 757, japanese: 'ヤトウモリ', chinese: '夜盗火蜥' },
  { name: 'Salazzle', id: 758, japanese: 'エンニュート', chinese: '焰后蜥' },
  { name: 'Stufful', id: 759, japanese: 'ヌイコグマ', chinese: '童偶熊' },
  { name: 'Bewear', id: 760, japanese: 'キテルグマ', chinese: '穿着熊' },
  { name: 'Bounsweet', id: 761, japanese: 'アマカジ', chinese: '甜竹竹' },
  { name: 'Steenee', id: 762, japanese: 'アママイコ', chinese: '甜舞妮' },
  { name: 'Tsareena', id: 763, japanese: 'アマージョ', chinese: '甜冷美后' },
  { name: 'Comfey', id: 764, japanese: 'キュワワー', chinese: '花疗环环' },
  { name: 'Oranguru', id: 765, japanese: 'ヤレユータン', chinese: '智挥猩' },
  { name: 'Passimian', id: 766, japanese: 'ナゲツケサル', chinese: '投掷猴' },
  { name: 'Wimpod', id: 767, japanese: 'コソクムシ', chinese: '胆小虫' },
  { name: 'Golisopod', id: 768, japanese: 'グソクムシャ', chinese: '具甲武者' },
  { name: 'Sandygast', id: 769, japanese: 'スナバァ', chinese: '沙丘娃' },
  { name: 'Palossand', id: 770, japanese: 'シロデスナ', chinese: '噬沙堡爷' },
  { name: 'Pyukumuku', id: 771, japanese: 'ナマコブシ', chinese: '拳海参' },
  {
    name: 'Type-Null',
    id: 772,
    japanese: 'タイプ：ヌル',
    chinese: '属性：空',
  },
  { name: 'Silvally', id: 773, japanese: 'シルヴァディ', chinese: '银伴战兽' },
  { name: 'Minior-Red-Meteor', id: 774, japanese: 'メテノ', chinese: '小陨星' },
  { name: 'Komala', id: 775, japanese: 'ネッコアラ', chinese: '树枕尾熊' },
  { name: 'Turtonator', id: 776, japanese: 'バクガメス', chinese: '爆焰龟兽' },
  {
    name: 'Togedemaru',
    id: 777,
    japanese: 'トゲデマル',
    chinese: '托戈德玛尔',
  },
  { name: 'Mimikyu-Disguised', id: 778, japanese: 'ミミッキュ', chinese: '谜拟丘' },
  { name: 'Bruxish', id: 779, japanese: 'ハギギシリ', chinese: '磨牙彩皮鱼' },
  { name: 'Drampa', id: 780, japanese: 'ジジーロン', chinese: '老翁龙' },
  { name: 'Dhelmise', id: 781, japanese: 'ダダリン', chinese: '破破舵轮' },
  { name: 'Jangmo-o', id: 782, japanese: 'ジャラコ', chinese: '心鳞宝' },
  { name: 'Hakamo-o', id: 783, japanese: 'ジャランゴ', chinese: '鳞甲龙' },
  { name: 'Kommo-o', id: 784, japanese: 'ジャラランガ', chinese: '杖尾鳞甲龙' },
  {
    name: 'Tapu-Koko',
    id: 785,
    japanese: 'カプ・コケコ',
    chinese: '卡璞・鸣鸣',
  },
  {
    name: 'Tapu-Lele',
    id: 786,
    japanese: 'カプ・テテフ',
    chinese: '卡璞・蝶蝶',
  },
  {
    name: 'Tapu-Bulu',
    id: 787,
    japanese: 'カプ・ブルル',
    chinese: '卡璞・哞哞',
  },
  {
    name: 'Tapu-Fini',
    id: 788,
    japanese: 'カプ・レヒレ',
    chinese: '卡璞・鳍鳍',
  },
  { name: 'Cosmog', id: 789, japanese: 'コスモッグ', chinese: '科斯莫古' },
  { name: 'Cosmoem', id: 790, japanese: 'コスモウム', chinese: '科斯莫姆' },
  { name: 'Solgaleo', id: 791, japanese: 'ソルガレオ', chinese: '索尔迦雷欧' },
  { name: 'Lunala', id: 792, japanese: 'ルナアーラ', chinese: '露奈雅拉' },
  { name: 'Nihilego', id: 793, japanese: 'ウツロイド', chinese: '虚吾伊德' },
  { name: 'Buzzwole', id: 794, japanese: 'マッシブーン', chinese: '爆肌蚊' },
  { name: 'Pheromosa', id: 795, japanese: 'フェローチェ', chinese: '费洛美螂' },
  { name: 'Xurkitree', id: 796, japanese: 'デンジュモク', chinese: '电束木' },
  { name: 'Celesteela', id: 797, japanese: 'テッカグヤ', chinese: '铁火辉夜' },
  { name: 'Kartana', id: 798, japanese: 'カミツルギ', chinese: '纸御剑' },
  { name: 'Guzzlord', id: 799, japanese: 'アクジキング', chinese: '恶食大王' },
  { name: 'Necrozma', id: 800, japanese: 'ネクロズマ', chinese: '奈克洛兹玛' },
  { name: 'Magearna', id: 801, japanese: 'マギアナ', chinese: '玛机雅娜' },
  { name: 'Marshadow', id: 802, japanese: 'マーシャドー', chinese: '玛夏多' },
  { name: 'Poipole', id: 803, japanese: 'ベベノム', chinese: '毒贝比' },
  { name: 'Naganadel', id: 804, japanese: 'アーゴヨン', chinese: '四颚针龙' },
  { name: 'Stakataka', id: 805, japanese: 'ツンデツンデ', chinese: '垒磊石' },
  { name: 'Blacephalon', id: 806, japanese: 'ズガドーン', chinese: '砰头小丑' },
  { name: 'Zeraora', id: 807, japanese: 'ゼラオラ', chinese: '捷拉奥拉' },
  { name: 'Meltan', id: 808, japanese: 'メルタン', chinese: '美录坦' },
  { name: 'Melmetal', id: 809, japanese: 'メルメタル', chinese: '美录梅塔' },
  { name: 'Grookey', id: 810, japanese: 'サルノリ', chinese: '敲音猴' },
  { name: 'Thwackey', id: 811, japanese: 'バチンキー', chinese: '啪咚猴' },
  {
    name: 'Rillaboom',
    id: 812,
    japanese: 'ゴリランダー',
    chinese: '轰擂金刚猩',
  },
  { name: 'Scorbunny', id: 813, japanese: 'ヒバニー', chinese: '炎兔儿' },
  { name: 'Raboot', id: 814, japanese: 'ラビフット', chinese: '腾蹴小将' },
  { name: 'Cinderace', id: 815, japanese: 'エースバーン', chinese: '闪焰王牌' },
  { name: 'Sobble', id: 816, japanese: 'メッソン', chinese: '泪眼蜥' },
  { name: 'Drizzile', id: 817, japanese: 'ジメレオン', chinese: '变涩蜥' },
  { name: 'Inteleon', id: 818, japanese: 'インテレオン', chinese: '千面避役' },
  { name: 'Skwovet', id: 819, japanese: 'ホシガリス', chinese: '贪心栗鼠' },
  { name: 'Greedent', id: 820, japanese: 'ヨクバリス', chinese: '藏饱栗鼠' },
  { name: 'Rookidee', id: 821, japanese: 'ココガラ', chinese: '稚山雀' },
  { name: 'Corvisquire', id: 822, japanese: 'アオガラス', chinese: '蓝鸦' },
  { name: 'Corviknight', id: 823, japanese: 'アーマーガア', chinese: '钢铠鸦' },
  { name: 'Blipbug', id: 824, japanese: 'サッチムシ', chinese: '索侦虫' },
  { name: 'Dottler', id: 825, japanese: 'レドームシ', chinese: '天罩虫' },
  { name: 'Orbeetle', id: 826, japanese: 'イオルブ', chinese: '以欧路普' },
  { name: 'Nickit', id: 827, japanese: 'クスネ', chinese: '狡小狐' },
  { name: 'Thievul', id: 828, japanese: 'フォクスライ', chinese: '猾大狐' },
  { name: 'Gossifleur', id: 829, japanese: 'ヒメンカ', chinese: '幼棉棉' },
  { name: 'Eldegoss', id: 830, japanese: 'ワタシラガ', chinese: '白蓬蓬' },
  { name: 'Wooloo', id: 831, japanese: 'ウールー', chinese: '毛辫羊' },
  { name: 'Dubwool', id: 832, japanese: 'バイウールー', chinese: '毛毛角羊' },
  { name: 'Chewtle', id: 833, japanese: 'カムカメ', chinese: '咬咬龟' },
  { name: 'Drednaw', id: 834, japanese: 'カジリガメ', chinese: '暴噬龟' },
  { name: 'Yamper', id: 835, japanese: 'ワンパチ', chinese: '来电汪' },
  { name: 'Boltund', id: 836, japanese: 'パルスワン', chinese: '逐电犬' },
  { name: 'Rolycoly', id: 837, japanese: 'タンドン', chinese: '小炭仔' },
  { name: 'Carkol', id: 838, japanese: 'トロッゴン', chinese: '大炭车' },
  { name: 'Coalossal', id: 839, japanese: 'セキタンザン', chinese: '巨炭山' },
  { name: 'Applin', id: 840, japanese: 'カジッチュ', chinese: '啃果虫' },
  { name: 'Flapple', id: 841, japanese: 'アップリュー', chinese: '苹裹龙' },
  { name: 'Appletun', id: 842, japanese: 'タルップル', chinese: '丰蜜龙' },
  { name: 'Silicobra', id: 843, japanese: 'スナヘビ', chinese: '沙包蛇' },
  { name: 'Sandaconda', id: 844, japanese: 'サダイジャ', chinese: '沙螺蟒' },
  { name: 'Cramorant', id: 845, japanese: 'ウッウ', chinese: '古月鸟' },
  { name: 'Arrokuda', id: 846, japanese: 'サシカマス', chinese: '刺梭鱼' },
  {
    name: 'Barraskewda',
    id: 847,
    japanese: 'カマスジョー',
    chinese: '戽斗尖梭',
  },
  { name: 'Toxel', id: 848, japanese: 'エレズン', chinese: '电音婴' },
  {
    name: 'Toxtricity-Amped',
    id: 849,
    japanese: 'ストリンダー',
    chinese: '颤弦蝾螈',
  },
  { name: 'Sizzlipede', id: 850, japanese: 'ヤクデ', chinese: '烧火蚣' },
  { name: 'Centiskorch', id: 851, japanese: 'マルヤクデ', chinese: '焚焰蚣' },
  { name: 'Clobbopus', id: 852, japanese: 'タタッコ', chinese: '拳拳蛸' },
  { name: 'Grapploct', id: 853, japanese: 'オトスパス', chinese: '八爪武师' },
  { name: 'Sinistea', id: 854, japanese: 'ヤバチャ', chinese: '来悲茶' },
  { name: 'Polteageist', id: 855, japanese: 'ポットデス', chinese: '怖思壶' },
  { name: 'Hatenna', id: 856, japanese: 'ミブリム', chinese: '迷布莉姆' },
  { name: 'Hattrem', id: 857, japanese: 'テブリム', chinese: '提布莉姆' },
  { name: 'Hatterene', id: 858, japanese: 'ブリムオン', chinese: '布莉姆温' },
  { name: 'Impidimp', id: 859, japanese: 'ベロバー', chinese: '捣蛋小妖' },
  { name: 'Morgrem', id: 860, japanese: 'ギモー', chinese: '诈唬魔' },
  { name: 'Grimmsnarl', id: 861, japanese: 'オーロンゲ', chinese: '长毛巨魔' },
  { name: 'Obstagoon', id: 862, japanese: 'タチフサグマ', chinese: '堵拦熊' },
  { name: 'Perrserker', id: 863, japanese: 'ニャイキング', chinese: '喵头目' },
  { name: 'Cursola', id: 864, japanese: 'サニゴーン', chinese: '魔灵珊瑚' },
  { name: 'Sirfetch’d', id: 865, japanese: 'ネギガナイト', chinese: '葱游兵' },
  { name: 'Mr-Rime', id: 866, japanese: 'バリコオル', chinese: '踏冰人偶' },
  { name: 'Runerigus', id: 867, japanese: 'デスバーン', chinese: '迭失板' },
  { name: 'Milcery', id: 868, japanese: 'マホミル', chinese: '小仙奶' },
  { name: 'Alcremie', id: 869, japanese: 'マホイップ', chinese: '霜奶仙' },
  { name: 'Falinks', id: 870, japanese: 'タイレーツ', chinese: '列阵兵' },
  { name: 'Pincurchin', id: 871, japanese: 'バチンウニ', chinese: '啪嚓海胆' },
  { name: 'Snom', id: 872, japanese: 'ユキハミ', chinese: '雪吞虫' },
  { name: 'Frosmoth', id: 873, japanese: 'モスノウ', chinese: '雪绒蛾' },
  { name: 'Stonjourner', id: 874, japanese: 'イシヘンジン', chinese: '巨石丁' },
  { name: 'Eiscue-Ice', id: 875, japanese: 'コオリッポ', chinese: '冰砌鹅' },
  { name: 'Indeedee-Male', id: 876, japanese: 'イエッサン', chinese: '爱管侍' },
  {
    name: 'Morpeko-Full-Belly',
    id: 877,
    japanese: 'モルペコ',
    chinese: '莫鲁贝可',
  },
  { name: 'Cufant', id: 878, japanese: 'ゾウドウ', chinese: '铜象' },
  {
    name: 'Copperajah',
    id: 879,
    japanese: 'ダイオウドウ',
    chinese: '大王铜象',
  },
  { name: 'Dracozolt', id: 880, japanese: 'パッチラゴン', chinese: '雷鸟龙' },
  { name: 'Arctozolt', id: 881, japanese: 'パッチルドン', chinese: '雷鸟海兽' },
  { name: 'Dracovish', id: 882, japanese: 'ウオノラゴン', chinese: '鳃鱼龙' },
  { name: 'Arctovish', id: 883, japanese: 'ウオチルドン', chinese: '鳃鱼海兽' },
  { name: 'Duraludon', id: 884, japanese: 'ジュラルドン', chinese: '铝钢龙' },
  { name: 'Dreepy', id: 885, japanese: 'ドラメシヤ', chinese: '多龙梅西亚' },
  { name: 'Drakloak', id: 886, japanese: 'ドロンチ', chinese: '多龙奇' },
  { name: 'Dragapult', id: 887, japanese: 'ドラパルト', chinese: '多龙巴鲁托' },
  { name: 'Zacian', id: 888, japanese: 'ザシアン', chinese: '苍响' },
  { name: 'Zamazenta', id: 889, japanese: 'ザマゼンタ', chinese: '藏玛然特' },
  { name: 'Eternatus', id: 890, japanese: 'ムゲンダイナ', chinese: '无极汰那' },
  { name: 'Kubfu', id: 891, japanese: 'ダクマ', chinese: '熊徒弟' },
  {
    name: 'Urshifu-Single-Strike',
    id: 892,
    japanese: 'ウーラオス',
    chinese: '武道熊师',
  },
  { name: 'Zarude', id: 893, japanese: 'ザルード', chinese: '萨戮德' },
  { name: 'Regieleki', id: 894, japanese: 'レジエレキ', chinese: '雷吉艾勒奇' },
  { name: 'Regidrago', id: 895, japanese: 'レジドラゴ', chinese: '雷吉铎拉戈' },
  { name: 'Glastrier', id: 896, japanese: 'ブリザポス', chinese: '雪暴马' },
  { name: 'Spectrier', id: 897, japanese: 'レイスポス', chinese: '灵幽马' },
  { name: 'Calyrex', id: 898, japanese: 'バドレックス', chinese: '蕾冠王' },
];
